#!/bin/bash
source ./docker/conf/config

if [ "$#" -lt 2 ]; then
    echo "Illegal number of parameters. You should use:"
    echo "  ./build <environment> <branch> [folder]"
    echo "  <environment> can be: Development or Production"
    echo "  [folder] is optional, usually you don't need to provide it if you already have an existing repository"
    exit
fi

if [ "$#" == 3 ]; then
	mkdir -p $3
	cp -rf . $3
	rm -rf $3/.git

	rm -rf $3/docker/conf/.gitignore
	rm -rf $3/docker/conf/config.sample

	cp -f $3/Readme.project.md $3/Readme.md
	rm -rf $3/Readme.project.md

	cd $3
fi

#Build docker image
docker build -t $image_name docker

#Run docker image
PWD=`pwd`
docker run -d -v $PWD:/app -p 80:80 -p 3306:3306 --name $image_name $image_name

# Change mysql password (We wait some time for mysql to start)
sleep 10
docker exec -i -t $image_name mysqladmin -u root -pAdmin2015 password $mysql_root_password

echo "docker exec -i -t ${image_name} /bin/bash" > docker/ssh
chmod 700 docker/ssh

#Deploy app
docker exec -i -t $image_name /app/docker/scripts/initial-deploy.sh $1 $2